openapi: 3.0.0
info:
  title: Columbus New API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /data/7:
    parameters:
      - required: true
      - required: true
    get:
      summary: ''
      operationId: get-data-7-research_station_code-plot_type
      responses:
        '200':
          description: OK
        '':
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        crop_id:
                          type: integer
                        parent_id:
                          type: string
                        source_id:
                          type:
                            - 'null'
                            - number
                        season:
                          type: string
                        year:
                          type: number
                        geom:
                          type:
                            - object
                            - 'null'
                        created_at:
                          type: string
                        updated_at:
                          type: string
                        status:
                          type: number
                        trial_id:
                          type: string
                        crop_code:
                          type: string
                        crop_name:
                          type: string
                        row_width:
                          type: string
                        row_length:
                          type: string
                        stage_code:
                          type: string
                        stage_name:
                          type: string
                        season_code:
                          type: string
                        country_code:
                          type: string
                        country_name:
                          type: string
                        trial_number:
                          type: string
                        experiment_id:
                          type: string
                        location_code:
                          type: string
                        location_name:
                          type: string
                        planting_date:
                          type: string
                        crop_type_code:
                          type: string
                        crop_type_name:
                          type: string
                        planting_area_id:
                          type: string
                        location_latitude:
                          type: string
                        location_selector:
                          type: string
                        trial_description:
                          type: string
                        location_longitude:
                          type: string
                        planting_area_code:
                          type: string
                        season_description:
                          type: string
                  total:
                    type: number
                  per_page:
                    type: string
                  current_page:
                    type: number
                  geometry_type:
                    type: string
              examples:
                trial example:
                  value:
                    data:
                      - id: c7311800-7fab-11ea-9102-133a5d899efb
                        crop_id: 1
                        parent_id: c3de91a0-7fab-11ea-b8bd-4118b7edf8c2
                        source_id: null
                        season: SUMR
                        year: 2019
                        geom: null
                        created_at: '2020-04-16T01:00:37.000Z'
                        updated_at: '2020-04-16T01:00:37.000Z'
                        status: '5'
                        trial_id: 19SUDWYG2023439
                        crop_code: CORN
                        crop_name: Corn
                        row_width: '76.2000'
                        row_length: '6.7056'
                        stage_code: '2'
                        stage_name: '2'
                        season_code: SUMR
                        country_code: US
                        country_name: United States
                        trial_number: '202'
                        experiment_id: 19SUDWYG202
                        location_code: '3439'
                        location_name: 'US Winthrop, MN 3439'
                        planting_date: '2019-05-16T00:00:00Z'
                        crop_type_code: YG
                        crop_type_name: Yield Grain trial
                        planting_area_id: c3de91a0-7fab-11ea-b8bd-4118b7edf8c2
                        location_latitude: '44.55981800'
                        location_selector: '3439:11-01-2018'
                        trial_description: SA Oct._IID3133CF_DH
                        location_longitude: '-94.35648000'
                        planting_area_code: 103N
                        season_description: Summer
                    total: 39255
                    per_page: '1'
                    current_page: 1
                    geometry_type: trial
      parameters:
        - schema:
            type: string
          in: query
          name: research_station_code
        - schema:
            type: string
          in: query
          name: plot_type
        - schema:
            type: string
          in: query
          name: location_selector
      description: ''
  /data/8:
    get:
      summary: Get data for plots
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        crop_id:
                          type: integer
                        fix_check_flag:
                          type: boolean
                        location_selector:
                          type: string
                        max_row:
                          type: string
                        min_row:
                          type: string
                        max_range:
                          type: string
                        min_range:
                          type: string
                        plot_id:
                          type: string
                        plot_geometry:
                          type: object
                        plot_area_usage:
                          type: array
                          items:
                            type: object
                            properties:
                              Vertical Coordinate:
                                type: string
                              Horizontal Coordinate:
                                type: string
                        material_id:
                          type: string
                        replicatio_number:
                          type: string
                        barcode:
                          type: string
                  total:
                    type: number
                  per_page:
                    type: string
                  current_page:
                    type: number
                  geometry_type:
                    type: string
              examples:
                Plot response:
                  value:
                    data:
                      - crop_id: 1
                        fix_check_flag: 'False'
                        location_selector: '6418:11-01-2019'
                        max_row: '188'
                        min_row: '187'
                        max_range: '25'
                        min_range: '25'
                        plot_id: '1049'
                        plot_geometry:
                          type: Polygon
                          coordinates:
                            - - - 72.86743084704328
                                - 21.30278287901389
                              - - 72.86743084704328
                                - 21.302843445028426
                              - - 72.86744553463056
                                - 21.302843445028426
                              - - 72.86744553463056
                                - 21.30278287901389
                              - - 72.86743084704328
                                - 21.30278287901389
                        plot_area_usage:
                          - Vertical Coordinate: '25'
                            Horizontal Coordinate: '187'
                          - Vertical Coordinate: '25'
                            Horizontal Coordinate: '188'
                        material_id: 20ALL1117UF_MM
                        replicatio_number: '1'
                        barcode: UR238135792
                    total: 1921999
                    per_page: '1'
                    current_page: 1
                    geometry_type: plot
      operationId: get-data-8
      parameters:
        - schema:
            type: string
          in: query
          name: crop_code
        - schema:
            type: string
          in: query
          name: research_station_code
        - schema:
            type: string
          in: query
          name: planting_area_code
        - schema:
            type: string
          in: query
          name: location_code
        - schema:
            type: string
          in: query
          name: location_selector
        - schema:
            type: string
          in: query
          name: experiment_id
        - schema:
            type: string
          in: query
          name: trial_id
        - schema:
            type: string
          in: query
          name: material_id
        - schema:
            type: string
          in: query
          name: year
  /data/9:
    get:
      summary: Get data for row
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        crop_id:
                          type:
                            - 'null'
                            - integer
                        planting_area_id:
                          type: string
                        trial_id:
                          type: string
                        exp_id:
                          type: string
                        plot_id:
                          type: string
                        material_id:
                          type: string
                  total:
                    type: integer
                  per_page:
                    type: string
                  current_page:
                    type: integer
                  geometry_type:
                    type: string
              examples:
                row response:
                  value:
                    data:
                      - crop_id: null
                        planting_area_id: c3de91a0-7fab-11ea-b8bd-4118b7edf8c2
                        trial_id: 19SUEGYG2153439
                        exp_id: '1'
                        plot_id: '1019'
                        material_id: 18EG820315
                    total: 6145
                    per_page: '1'
                    current_page: 1
                    geometry_type: row
      operationId: get-data-9
      parameters:
        - schema:
            type: string
          in: query
          name: crop_code
        - schema:
            type: string
          in: query
          name: research_station_code
        - schema:
            type: string
          in: query
          name: planting_area_code
        - schema:
            type: string
          in: query
          name: location_code
        - schema:
            type: string
          in: query
          name: location_selector
        - schema:
            type: string
          in: query
          name: experiment_id
        - schema:
            type: string
          in: query
          name: trial_id
        - schema:
            type: string
          in: query
          name: material_id
        - schema:
            type: string
          in: query
          name: year
  /data/10:
    get:
      summary: Get seed data
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        crop_id:
                          type:
                            - integer
                            - 'null'
                        seed_geometry:
                          type: object
              examples:
                seed response:
                  value:
                    data:
                      - crop_id: null
                        seed_geometry:
                          type: Point
                          coordinates:
                            - -95.04731792406912
                            - 41.37632822206144
                    total: 155502
                    per_page: '1'
                    current_page: 1
                    geometry_type: seed
      operationId: get-data-10
      parameters:
        - schema:
            type: string
          in: query
          name: crop_code
        - schema:
            type: string
          in: query
          name: research_station_code
        - schema:
            type: string
          in: query
          name: planting_area_code
        - schema:
            type: string
          in: query
          name: location_code
        - schema:
            type: string
          in: query
          name: location_selector
        - schema:
            type: string
          in: query
          name: experiment_id
        - schema:
            type: string
          in: query
          name: trial_id
        - schema:
            type: string
          in: query
          name: material_id
        - schema:
            type: string
          in: query
          name: year
  /crops:
    get:
      summary: Get list of crops
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
              examples:
                response:
                  value:
                    - id: '2'
                      name: Soybean
                    - id: '1'
                      name: Corn
      operationId: get-crops
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples: {}
  /geometry-types:
    get:
      summary: Get list of geometry types
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
              examples:
                response:
                  value:
                    - id: '1'
                      name: research_station
                    - id: '2'
                      name: location
                    - id: '3'
                      name: aoi
                    - id: '4'
                      name: trialing_aoi
                    - id: '5'
                      name: test_fit_plot
                    - id: '6'
                      name: planting_area
                    - id: '7'
                      name: trial
                    - id: '8'
                      name: plot
                    - id: '9'
                      name: row
                    - id: '10'
                      name: seed
                    - id: '11'
                      name: unplantable_area
                    - id: '34'
                      name: trimble_data
                    - id: '35'
                      name: multi_polygon
                    - id: '36'
                      name: multi_line_string
                    - id: '37'
                      name: multi_point
                    - id: '38'
                      name: polygon
                    - id: '39'
                      name: line_string
                    - id: '40'
                      name: point
                    - id: '41'
                      name: shapefile
                    - id: '42'
                      name: zonal_stats_data
                    - id: '43'
                      name: kml
      operationId: get-geometry-types
components:
  schemas: {}
